### ISSUE TITLE
How run in Xcode?

### ISSUE THREAD

**Issue by ChokWah** [tokoik/fisheye#1]
Hi , Tokoik . I want to run your project, something's wrong.

Xcode show : 'GLFW/glfw3.h' file not found.
It seen need to add "$PROJECT_DIR/fisheye".But where place should I set this "$PROJECT_DIR/fisheye".

**Comment by tokoik** [comment]
Please click the button labeled "fisheye" in the upper left corner of Xcode and choose "edit scheme." Next, select "Run" from the left pane, then choose the "Options" tab. Then check the "Use custom working directory" in the "Working Directory" and enter "$(PROJECT_DIR)/fisheye" in the box below it.

**Comment by ottonove** [comment]
Even if the above setting is used, it will not work because "Opencv2 / highgui / highgui.hpp 'file is not found".
Please let me know if there are any other points to note.

**Comment by tokoik** [comment]
I added GLFW and OpenCV library files for macOS yesterday to this project. I confirmed that I can build with Xcode. Perhaps you can build without HomeBrew.

**Comment by ottonove** [comment]
It worked. Thank you very much!
